### ISSUE TITLE
Remove Buffer API usage

### ISSUE THREAD

**Issue by tfalencar** [ldthomas/apg-js#9] opened 2022-11-14 22:08 UTC
In some environments, the Node.js Buffer API as used by this project is not available. I'm not super familiar with node/js, but I noticed some projects replace it with packages like https://www.npmjs.com/package/safer-buffer . 

This project is a dependency from a library I'm trying to use (https://github.com/spruceid/siwe). Would it be desired/conceivable to adapt this project to drop the native Buffer API usage?

**Comment by ldthomas** [comment] 2022-11-19 12:42
apg-js was designed to have zero dependencies and to work with Node.js (developed with version 15.11.0). So adding a dependency would break one of my primary design features. I haven't worked with JavaScript for a couple of years now and don't have the time or motivation to understand what the underlying problem is and make any significant changes anyway. But thanks for your interest in apg-js.

**Comment by tfalencar** [comment] 2022-11-20 21:03
Thanks for the feedback; Closing this issue.

**Comment by mrose17** [comment] 2023-03-22 14:53
@ldthomas - sorry to chime in on this. so, what is the preferred solution for putting Buffer into something that's going to use `apg-js` in the browser? Here's what I'm doing:

        global.Buffer = require("buffer/").Buffer;

which seems kind of "hacky"... thanks!

**Comment by ldthomas** [comment] 2023-03-23 20:32
As I mentioned above, it's been a couple of years since I've worked with this. As far as I can reconstruct (and I haven't spent a lot of time on this) the Node.js Buffer is only exported in:
_apg-js/src/apg-conv-api/web-exports.js_

However, apg-conv-api is used by all of the other libraries so it will get pulled in with apg-api-bundle.js.

I've only used browserify for bundling. It gets bundled for use in a web browser in :
_apg-js/bin/apg-conv-api-bundle.sh_

You can see an example of how that is used in a web page at:
_apg-js-examples/src/apg-api/web-apg-api.js_
and
_apg-js-examples/src/apg-api/web-apg-api.html_

Don't know if that helps but that is the way I did it.

**Comment by mrose17** [comment] 2023-03-24 14:04
Thank you! I've gone through several permutations of requiring `web-exports` and `apg-js`, and haven't hit the right permutation yet. it may be something with TypeScript, etc., and eventually I can figure it out.

Regardless, let's close this issue. I have a solution, and more importantly you've already dealt with it in the package. So I think we're good!

**Comment by ldthomas** [comment] 2023-03-24 14:38
Good luck with your project and thanks for using APG.

**Closed as completed by ldthomas** 2023-03-24 14:38 UTC
